apiVersion: v1
kind: Service
metadata:
  name: helm-order-service
spec:
  type: NodePort
  selector:
    app: helm-order-service
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 31470  # NodePort range is typically between 30000-32767

